from enum import Enum
import Appendectomy as App

SURGERY_PROB = App.APP_SURGERY_PROB
NO_SURGERY_DEATH_PROB = App.APP_NO_SURGERY_DEATH_PROB
SURGEON_ACCESS_PROB = 0
SURGEON_DEATH_PROB = App.APP_DEATH_PROB
COMPLICATION_PROB = App.APP_COMPLICATION_PROB
MAJOR_COMPLICATION_PROB = 0
MINOR_COMPLICATION_PROB = 0
MAJOR_COMPLICATION_DEATH_PROB = App.APP_COMPLICATION_DEATH_PROB
NONSURGEON_DEATH_PROB = 0

class HealthState(Enum):
    HEALTHY = 0  # no health problems  # do we need this??
    SURGERY = 1  # patient now requires surgery

